CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    EmailAddress VARCHAR(50) NOT NULL
);

CREATE TABLE Customers (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Address VARCHAR(100) NOT NULL,
    EmailAddress VARCHAR(20) NOT NULL,
    Age int NOT NULL,
    Phone VARCHAR(15) NOT NULL UNIQUE
);
